### PR TITLE
Binary To Decimal

### PR DESCRIPTION
**Pull request by Zaid-Parkar**

### CODE REVIEW

**Comment by satyamagrawalread** [comment]
Hi @Zaid-Parkar ,
Please go through the question link given, and write only code inside the function given.
And, first submit the code in GFG. If your get submitted successfully then only add here in the format mentioned in readme.
In case function is not given then only write your own functions.
Keep going👍

**Comment by Zaid-Parkar** [comment]
@satyamagrawalread Okay 👍, will do the necessary changes in code also do let me know how can I update my code on GitHub or I need to create new pull request .

**Comment by satyamagrawalread** [comment]
@Zaid-Parkar create a new pull request and make sure to follow the given format.

**Comment by Zaid-Parkar** [comment]
okay 👍

**Comment by Zaid-Parkar** [comment]
@satyamagrawalread  I have updated code  and its working fine on GFG. I have created new pull request for it , review my other code also.

**Pull request closed without merging**
